-- 帳戶查詢服務 schema（讀取側 + 優惠寫入側）

CREATE TABLE account (
    account_id   VARCHAR(14) PRIMARY KEY,
    owner_id     VARCHAR(64) NOT NULL,
    account_type VARCHAR(8)  NOT NULL,
    currency     VARCHAR(8)  NOT NULL,
    status       VARCHAR(16) NOT NULL
);
CREATE INDEX idx_account_owner ON account (owner_id);

CREATE TABLE transaction (
    transaction_id   VARCHAR(64) PRIMARY KEY,
    account_id       VARCHAR(14) NOT NULL REFERENCES account (account_id),
    type             VARCHAR(8)  NOT NULL,
    amount           NUMERIC(19, 2) NOT NULL,
    amount_currency  VARCHAR(8)  NOT NULL,
    twd_equivalent   NUMERIC(19, 2),
    transaction_date TIMESTAMP   NOT NULL,
    description      VARCHAR(255),
    channel          VARCHAR(16) NOT NULL
);
CREATE INDEX idx_tx_account_date ON transaction (account_id, transaction_date);

CREATE TABLE transfer_privilege (
    privilege_id VARCHAR(64) PRIMARY KEY,
    owner_id     VARCHAR(64) NOT NULL,
    type         VARCHAR(48) NOT NULL,
    total_quota  INTEGER     NOT NULL,
    used_quota   INTEGER     NOT NULL,
    valid_from   DATE        NOT NULL,
    valid_to     DATE        NOT NULL
);
CREATE INDEX idx_privilege_owner ON transfer_privilege (owner_id);

CREATE TABLE privilege_usage_record (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    privilege_id      VARCHAR(64) NOT NULL REFERENCES transfer_privilege (privilege_id),
    used_date         DATE        NOT NULL,
    saved_amount      NUMERIC(19, 2) NOT NULL,
    target_account_no VARCHAR(64) NOT NULL
);
CREATE INDEX idx_usage_privilege ON privilege_usage_record (privilege_id);
