-- 事件溯源：優惠聚合的 append-only 事件庫。
-- 以 (aggregate_id, sequence_no) 唯一鍵保證每個聚合的事件順序與樂觀並行控制。

CREATE TABLE privilege_event (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id      VARCHAR(64) NOT NULL,
    sequence_no       INTEGER     NOT NULL,
    event_type        VARCHAR(48) NOT NULL,
    occurred_on       TIMESTAMP   NOT NULL,
    -- 共用：核發事件的對象 / 使用事件的客戶
    subject_id        VARCHAR(64),
    -- TransferPrivilegeGranted 欄位
    priv_type         VARCHAR(48),
    total_quota       INTEGER,
    valid_from        DATE,
    valid_to          DATE,
    -- TransferPrivilegeUsed 欄位
    saved_amount      NUMERIC(19, 2),
    used_date         DATE,
    target_account_no VARCHAR(64),
    remaining_quota   INTEGER,
    CONSTRAINT uq_privilege_event_seq UNIQUE (aggregate_id, sequence_no)
);
CREATE INDEX idx_privilege_event_agg ON privilege_event (aggregate_id, sequence_no);
