-- 由領域事件消費端（@EventListener）寫入的稽核日誌（事件 → 副作用 的示範）。
CREATE TABLE privilege_audit_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type   VARCHAR(48) NOT NULL,
    privilege_id VARCHAR(64) NOT NULL,
    customer_id  VARCHAR(64) NOT NULL,
    occurred_on  TIMESTAMP   NOT NULL,
    detail       VARCHAR(255)
);
CREATE INDEX idx_audit_privilege ON privilege_audit_log (privilege_id);
